-- 60 launch questions (same bank as the clickable prototype).
-- Launch day is the day you run this: "Is the Earth flat?" goes live today,
-- then one week-one question a day. After that ensure_daily() keeps the
-- slot filled from the rest of the bank.
insert into public.questions (text, category, sensitivity, option_yes, option_no, emoji_yes, emoji_no, partner, daily_date) values
  ('Is the Earth flat?', 'Big debates', 'standard', null, null, null, null, null, public.today_uk() + 0),
  ('Nike or Reebok?', 'Brands', 'standard', 'Nike', 'Reebok', '✔️', '🇬🇧', null, public.today_uk() + 5),
  ('Can you run 5k?', 'Fitness', 'personal', null, null, null, null, 'Strava', null),
  ('Is a hot dog a sandwich?', 'Food', 'standard', null, null, null, null, null, public.today_uk() + 1),
  ('Beach or mountains?', 'Lifestyle', 'standard', 'Beach', 'Mountains', '🏖️', '🏔️', null, null),
  ('Is it OK to recline your seat on a plane?', 'Ethics', 'standard', null, null, null, null, null, public.today_uk() + 3),
  ('Should pineapple go on pizza?', 'Food', 'standard', null, null, null, null, null, public.today_uk() + 4),
  ('Did humans really land on the Moon in 1969?', 'Big debates', 'standard', null, null, null, null, null, null),
  ('iPhone or Android?', 'Brands', 'standard', 'iPhone', 'Android', '🍎', '🤖', null, null),
  ('Coke or Pepsi?', 'Brands', 'standard', 'Coke', 'Pepsi', '🔴', '🔵', null, null),
  ('Adidas or Puma?', 'Brands', 'standard', 'Adidas', 'Puma', '⛰️', '🐆', null, null),
  ('Tea or coffee?', 'Food', 'standard', 'Tea', 'Coffee', '🍵', '☕', null, null),
  ('Would you pay more for a brand that never sells your data?', 'Brands', 'standard', null, null, null, null, null, null),
  ('McDonald''s or Burger King?', 'Brands', 'standard', 'McDonald''s', 'Burger King', '🍟', '👑', null, null),
  ('Have you run a half marathon?', 'Fitness', 'personal', null, null, null, null, 'Strava', null),
  ('Have you cycled 50 km in one ride?', 'Fitness', 'personal', null, null, null, null, 'Strava', null),
  ('Do you exercise three or more times a week?', 'Fitness', 'personal', null, null, null, null, 'Strava', null),
  ('Can you swim 1 km without stopping?', 'Fitness', 'personal', null, null, null, null, 'Strava', null),
  ('Do you walk 10,000 steps on most days?', 'Fitness', 'personal', null, null, null, null, 'Apple Health', null),
  ('Do you sleep seven hours or more most nights?', 'Lifestyle', 'personal', null, null, null, null, 'Apple Health', null),
  ('Early bird or night owl?', 'Lifestyle', 'standard', 'Early bird', 'Night owl', '🐦', '🦉', null, null),
  ('Do you want children one day?', 'Dating', 'personal', null, null, null, null, null, null),
  ('Do you believe in love at first sight?', 'Dating', 'standard', null, null, null, null, null, null),
  ('Should you split the bill on a first date?', 'Dating', 'standard', null, null, null, null, null, null),
  ('Would you date someone who places bets?', 'Dating', 'standard', null, null, null, null, null, null),
  ('Would you move country for a partner?', 'Dating', 'standard', null, null, null, null, null, null),
  ('Cats or dogs?', 'Lifestyle', 'standard', 'Cats', 'Dogs', '🐱', '🐶', null, public.today_uk() + 6),
  ('Are you vegetarian or vegan?', 'Food', 'personal', null, null, null, null, null, null),
  ('Do you drink alcohol?', 'Lifestyle', 'personal', null, null, null, null, null, null),
  ('Do you smoke or vape?', 'Lifestyle', 'personal', null, null, null, null, null, null),
  ('Do you believe in God?', 'Beliefs', 'sensitive', null, null, null, null, null, null),
  ('Do you pray regularly?', 'Beliefs', 'sensitive', null, null, null, null, null, null),
  ('Do you believe in life after death?', 'Beliefs', 'sensitive', null, null, null, null, null, null),
  ('Should the UK rejoin the EU?', 'Politics', 'sensitive', null, null, null, null, null, null),
  ('Should the monarchy be abolished?', 'Politics', 'sensitive', null, null, null, null, null, null),
  ('Did you vote in the last general election?', 'Politics', 'sensitive', null, null, null, null, null, null),
  ('Should voting be compulsory?', 'Politics', 'sensitive', null, null, null, null, null, null),
  ('Should cannabis be legal in the UK?', 'Politics', 'sensitive', null, null, null, null, null, null),
  ('Should the UK bring back the death penalty?', 'Politics', 'sensitive', null, null, null, null, null, null),
  ('Do you support a universal basic income?', 'Politics', 'sensitive', null, null, null, null, null, null),
  ('Would you return a lost wallet with the cash still inside?', 'Ethics', 'standard', null, null, null, null, null, null),
  ('Have you ever cheated at a board game?', 'Ethics', 'standard', null, null, null, null, null, null),
  ('Would you tell a friend their partner was cheating?', 'Ethics', 'standard', null, null, null, null, null, null),
  ('Is it OK to lie on your CV?', 'Ethics', 'standard', null, null, null, null, null, null),
  ('Would you bet against your own team?', 'Ethics', 'standard', null, null, null, null, null, null),
  ('Do you save money every month?', 'Money', 'personal', null, null, null, null, null, null),
  ('Do you own any crypto?', 'Money', 'personal', null, null, null, null, null, null),
  ('Have you placed a bet in the last year?', 'Money', 'personal', null, null, null, null, null, null),
  ('Rent or buy your home?', 'Money', 'standard', 'Rent', 'Buy', '🏢', '🏡', null, null),
  ('Will AI be able to do your job within ten years?', 'Tech', 'standard', null, null, null, null, null, null),
  ('Do you check your phone within five minutes of waking up?', 'Tech', 'standard', null, null, null, null, null, null),
  ('Should under-16s be banned from social media?', 'Tech', 'standard', null, null, null, null, null, null),
  ('Work from home or the office?', 'Tech', 'standard', 'Home', 'Office', '🏠', '🏙️', null, null),
  ('Would you ride in a self-driving car today?', 'Tech', 'standard', null, null, null, null, null, null),
  ('Do aliens exist?', 'Wild cards', 'standard', null, null, null, null, null, null),
  ('Would you want to know the date you''ll die?', 'Wild cards', 'standard', null, null, null, null, null, null),
  ('Would you take a one-way ticket to Mars?', 'Big debates', 'standard', null, null, null, null, null, public.today_uk() + 2),
  ('Is time travel possible?', 'Wild cards', 'standard', null, null, null, null, null, null),
  ('Can you do 20 push-ups in a row?', 'Fitness', 'personal', null, null, null, null, null, null),
  ('Have you lived in another country?', 'Lifestyle', 'standard', null, null, null, null, null, null);

-- World events for the Predict tab. Settle them with resolve_event(id, outcome).
insert into public.questions (text, category, is_event, closes_at) values
  ('Will it snow in London on Christmas Day 2026?', 'World events', true, '2026-12-24 23:59:00+00'),
  ('Will a crewed mission land on the Moon before 2028?', 'World events', true, '2027-12-31 23:59:00+00');
