-- The question bank: 230 new questions across all 20 themes.
--
-- Written to split the room: funny ones (straw holes, Ross and Rachel),
-- thoughtful ones (the trolley problem, the experience machine) and spicy
-- ones (split the bill, quiet quitting). Lifestyle has four picks that line
-- up with the 16 personalities axes, and Beliefs has horoscope lead-ins.
-- Fate, karma and star signs are open to everyone; religion and politics
-- stay behind the 18+ opt-in.
--
-- Safe to run twice: questions already in the bank are skipped.

insert into public.questions (text, category, sensitivity, option_yes, option_no, emoji_yes, emoji_no)
select v.text, v.category, v.sensitivity::public.sensitivity, v.option_yes, v.option_no, v.emoji_yes, v.emoji_no
from (values
  ('Does a straw have one hole or two?', 'Big debates', 'standard', 'One', 'Two', '1️⃣', '2️⃣'),
  ('Is water wet?', 'Big debates', 'standard', null, null, null, null),
  ('Does money buy happiness?', 'Big debates', 'standard', null, null, null, null),
  ('Is human nature basically good?', 'Big debates', 'standard', null, null, null, null),
  ('Is free will an illusion?', 'Big debates', 'standard', null, null, null, null),
  ('Would you plug into a machine that gave you a perfect fake life?', 'Big debates', 'standard', null, null, null, null),
  ('Should we bring the woolly mammoth back?', 'Big debates', 'standard', null, null, null, null),
  ('Should zoos exist?', 'Big debates', 'standard', null, null, null, null),
  ('Would you rather be right or be liked?', 'Big debates', 'standard', 'Right', 'Liked', '🧠', '🤝'),
  ('Glass half full or half empty?', 'Big debates', 'standard', 'Half full', 'Half empty', '🥛', '🫗'),
  ('Is it better to be feared than loved?', 'Big debates', 'standard', null, null, null, null),
  ('Is a Pop-Tart a ravioli?', 'Big debates', 'standard', null, null, null, null),
  ('Would you push one person off a bridge to save five?', 'Ethics', 'standard', null, null, null, null),
  ('Would you pull a lever to kill one person and save five?', 'Ethics', 'standard', null, null, null, null),
  ('Would you keep £500 your bank paid you by mistake?', 'Ethics', 'standard', null, null, null, null),
  ('Is it OK to scan avocados as onions at the self-checkout?', 'Ethics', 'standard', null, null, null, null),
  ('Is it OK to leave your trolley in the car park?', 'Ethics', 'standard', null, null, null, null),
  ('Should you tip when the service was bad?', 'Ethics', 'standard', null, null, null, null),
  ('Is it OK to regift a present?', 'Ethics', 'standard', null, null, null, null),
  ('Would you lie to get your child into a better school?', 'Ethics', 'standard', null, null, null, null),
  ('Would you take double the pay to work for a company you thought was unethical?', 'Ethics', 'standard', null, null, null, null),
  ('Would you give a kidney to a stranger?', 'Ethics', 'standard', null, null, null, null),
  ('Is it wrong to eat meat?', 'Ethics', 'standard', null, null, null, null),
  ('Is fast fashion OK if it''s all you can afford?', 'Ethics', 'standard', null, null, null, null),
  ('Is it OK to eat food in the supermarket before paying?', 'Ethics', 'standard', null, null, null, null),
  ('Would you report a colleague for fiddling their expenses?', 'Ethics', 'standard', null, null, null, null),
  ('Can men and women ever just be friends?', 'Dating', 'standard', null, null, null, null),
  ('Is it OK to go through your partner''s phone if you suspect them?', 'Dating', 'standard', null, null, null, null),
  ('Is ghosting ever acceptable?', 'Dating', 'standard', null, null, null, null),
  ('Is liking an ex''s photos a kind of cheating?', 'Dating', 'standard', null, null, null, null),
  ('Would you get back with an ex?', 'Dating', 'personal', null, null, null, null),
  ('Should you stay friends with your exes?', 'Dating', 'standard', null, null, null, null),
  ('Would you sign a prenup?', 'Dating', 'standard', null, null, null, null),
  ('Would you date someone ten years older than you?', 'Dating', 'standard', null, null, null, null),
  ('Would you date someone shorter than you?', 'Dating', 'standard', null, null, null, null),
  ('Is a long-distance relationship worth it?', 'Dating', 'standard', null, null, null, null),
  ('Funny or good-looking?', 'Dating', 'standard', 'Funny', 'Good-looking', '😂', '😍'),
  ('Do you still have photos of an ex on your phone?', 'Dating', 'personal', null, null, null, null),
  ('Should the person who asked pay on a first date?', 'Dating', 'standard', null, null, null, null),
  ('Should you know how many people your partner has slept with?', 'Dating', 'standard', null, null, null, null),
  ('Were Ross and Rachel on a break?', 'Film & TV', 'standard', null, null, null, null),
  ('Could Jack have fitted on the door in Titanic?', 'Film & TV', 'standard', null, null, null, null),
  ('Did Game of Thrones ruin its ending?', 'Film & TV', 'standard', null, null, null, null),
  ('UK Office or US Office?', 'Film & TV', 'standard', 'UK', 'US', '🇬🇧', '🇺🇸'),
  ('Friends or Gavin & Stacey?', 'Film & TV', 'standard', 'Friends', 'Gavin & Stacey', '☕', '🏴'),
  ('Star Wars or Lord of the Rings?', 'Film & TV', 'standard', 'Star Wars', 'Lord of the Rings', '⚔️', '💍'),
  ('Should James Bond ever be played by a woman?', 'Film & TV', 'standard', null, null, null, null),
  ('Have you ever pretended to have seen a film you haven''t?', 'Film & TV', 'standard', null, null, null, null),
  ('Is a remake ever better than the original?', 'Film & TV', 'standard', null, null, null, null),
  ('Is Love Actually actually good?', 'Film & TV', 'standard', null, null, null, null),
  ('Binge the whole series or one episode a week?', 'Film & TV', 'standard', 'Binge', 'Weekly', '🍿', '📅'),
  ('Is it OK to talk during a film?', 'Film & TV', 'standard', null, null, null, null),
  ('Is Shrek a masterpiece?', 'Film & TV', 'standard', null, null, null, null),
  ('Is going to the gym on holiday a red flag?', 'Fitness', 'standard', null, null, null, null),
  ('Have you ever paid for a gym you never went to?', 'Fitness', 'standard', null, null, null, null),
  ('Do you really need 10,000 steps a day?', 'Fitness', 'standard', null, null, null, null),
  ('Is running boring?', 'Fitness', 'standard', null, null, null, null),
  ('Is yoga a proper workout?', 'Fitness', 'standard', null, null, null, null),
  ('Is a cold plunge worth the hype?', 'Fitness', 'standard', null, null, null, null),
  ('Can you touch your toes without bending your knees?', 'Fitness', 'personal', null, null, null, null),
  ('Can you hold a plank for two minutes?', 'Fitness', 'personal', null, null, null, null),
  ('Can you do a pull-up?', 'Fitness', 'personal', null, null, null, null),
  ('Should PE be compulsory until you leave school?', 'Fitness', 'standard', null, null, null, null),
  ('Dinner or tea for your evening meal?', 'Food', 'standard', 'Dinner', 'Tea', '🍽️', '🫖'),
  ('Cream or jam first on a scone?', 'Food', 'standard', 'Cream', 'Jam', '🐄', '🍓'),
  ('Red or brown sauce on a bacon sandwich?', 'Food', 'standard', 'Red', 'Brown', '🍅', '🟤'),
  ('Marmite: love it or hate it?', 'Food', 'standard', 'Love', 'Hate', '😋', '🤢'),
  ('Cereal first or milk first?', 'Food', 'standard', 'Cereal', 'Milk', '🥣', '🥛'),
  ('Is it OK to eat pizza with a knife and fork?', 'Food', 'standard', null, null, null, null),
  ('Is it rude to take the last slice?', 'Food', 'standard', null, null, null, null),
  ('Is Christmas dinner overrated?', 'Food', 'standard', null, null, null, null),
  ('Is it OK to send food back at a restaurant?', 'Food', 'standard', null, null, null, null),
  ('Would you eat insects if they were better for the planet?', 'Food', 'standard', null, null, null, null),
  ('Is a chip butty a proper meal?', 'Food', 'standard', null, null, null, null),
  ('Do you eat your crusts?', 'Food', 'standard', null, null, null, null),
  ('Is sushi overrated?', 'Food', 'standard', null, null, null, null),
  ('Will humans live on Mars in your lifetime?', 'Future', 'standard', null, null, null, null),
  ('Would you upload your mind to a computer?', 'Future', 'standard', null, null, null, null),
  ('Would you eat lab-grown meat?', 'Future', 'standard', null, null, null, null),
  ('Would you let an AI pick your partner?', 'Future', 'standard', null, null, null, null),
  ('Would you freeze your body to be brought back in the future?', 'Future', 'standard', null, null, null, null),
  ('Will your generation be better off than your parents''?', 'Future', 'standard', null, null, null, null),
  ('Should we try to contact aliens?', 'Future', 'standard', null, null, null, null),
  ('Would you edit your baby''s genes to prevent disease?', 'Future', 'standard', null, null, null, null),
  ('Should humans be banned from driving once self-driving cars are safer?', 'Future', 'standard', null, null, null, null),
  ('Would you take a pill so you never needed to sleep?', 'Future', 'standard', null, null, null, null),
  ('Will we have flying taxis by 2035?', 'Future', 'standard', null, null, null, null),
  ('Are you secretly happy when plans get cancelled?', 'Lifestyle', 'standard', null, null, null, null),
  ('Toilet roll over or under?', 'Lifestyle', 'standard', 'Over', 'Under', '🔝', '⬇️'),
  ('Shower in the morning or at night?', 'Lifestyle', 'standard', 'Morning', 'Night', '🌅', '🌙'),
  ('Shoes off at a friend''s house?', 'Lifestyle', 'standard', null, null, null, null),
  ('Do you sleep with one foot out of the duvet?', 'Lifestyle', 'standard', null, null, null, null),
  ('Do you make your bed every morning?', 'Lifestyle', 'standard', null, null, null, null),
  ('Is it weird to go to the cinema alone?', 'Lifestyle', 'standard', null, null, null, null),
  ('Text or call?', 'Lifestyle', 'standard', 'Text', 'Call', '💬', '📞'),
  ('Introvert or extrovert?', 'Lifestyle', 'standard', 'Introvert', 'Extrovert', '🏠', '🎉'),
  ('Plan everything or wing it?', 'Lifestyle', 'standard', 'Plan', 'Wing it', '📋', '🎲'),
  ('Head or heart?', 'Lifestyle', 'standard', 'Head', 'Heart', '🧠', '❤️'),
  ('Big picture or the details?', 'Lifestyle', 'standard', 'Big picture', 'Details', '🔭', '🔍'),
  ('Do you talk to your pets like they''re people?', 'Lifestyle', 'standard', null, null, null, null),
  ('Is it rude to turn up to a party empty-handed?', 'Lifestyle', 'standard', null, null, null, null),
  ('Split the bill evenly or by what you had?', 'Money', 'standard', 'Evenly', 'What you had', '➗', '🧾'),
  ('£1 million now or £50k a year for life?', 'Money', 'standard', '£1m now', '£50k a year', '💰', '📆'),
  ('Should couples have a joint bank account?', 'Money', 'standard', null, null, null, null),
  ('Would you lend a friend £500?', 'Money', 'standard', null, null, null, null),
  ('Is it rude to ask someone what they earn?', 'Money', 'standard', null, null, null, null),
  ('Would you quit social media forever for £100,000?', 'Money', 'standard', null, null, null, null),
  ('Is the lottery a waste of money?', 'Money', 'standard', null, null, null, null),
  ('Is a 12.5% service charge too much?', 'Money', 'standard', null, null, null, null),
  ('Should you pay your kids for doing chores?', 'Money', 'standard', null, null, null, null),
  ('Should parents split their inheritance equally between children?', 'Money', 'standard', null, null, null, null),
  ('Is giving cash as a present lazy?', 'Money', 'standard', null, null, null, null),
  ('Do you know roughly how much is in your bank account right now?', 'Money', 'personal', null, null, null, null),
  ('Is it OK to play music out loud on the bus?', 'Music', 'standard', null, null, null, null),
  ('Is it OK to film a whole gig on your phone?', 'Music', 'standard', null, null, null, null),
  ('Is Christmas music before December a crime?', 'Music', 'standard', null, null, null, null),
  ('Is Mr Brightside the best song ever written?', 'Music', 'standard', null, null, null, null),
  ('Should ticket prices be capped by law?', 'Music', 'standard', null, null, null, null),
  ('Ed Sheeran or Adele?', 'Music', 'standard', 'Ed Sheeran', 'Adele', '🎸', '🎤'),
  ('Is Taylor Swift the greatest songwriter of her generation?', 'Music', 'standard', null, null, null, null),
  ('Would you go to a concert on your own?', 'Music', 'standard', null, null, null, null),
  ('Is AI-made music real music?', 'Music', 'standard', null, null, null, null),
  ('Do you sing in the shower?', 'Music', 'standard', null, null, null, null),
  ('Is Wonderwall overplayed?', 'Music', 'standard', null, null, null, null),
  ('Should artists get paid more per stream?', 'Music', 'standard', null, null, null, null),
  ('Are we living in a simulation?', 'Mysteries', 'standard', null, null, null, null),
  ('Did one man really write all of Shakespeare?', 'Mysteries', 'standard', null, null, null, null),
  ('Do psychics have real powers?', 'Mysteries', 'standard', null, null, null, null),
  ('Will Jack the Ripper ever be identified?', 'Mysteries', 'standard', null, null, null, null),
  ('Is déjà vu a glitch in your brain?', 'Mysteries', 'standard', null, null, null, null),
  ('Have you ever seen something you couldn''t explain?', 'Mysteries', 'standard', null, null, null, null),
  ('Are dreams trying to tell us something?', 'Mysteries', 'standard', null, null, null, null),
  ('Is there life in the oceans under Europa''s ice?', 'Mysteries', 'standard', null, null, null, null),
  ('Is the Bermuda Triangle more dangerous than anywhere else?', 'Mysteries', 'standard', null, null, null, null),
  ('Do you still know your childhood landline number?', 'Nostalgia', 'standard', null, null, null, null),
  ('Was MSN Messenger better than WhatsApp?', 'Nostalgia', 'standard', null, null, null, null),
  ('Did you have a MySpace?', 'Nostalgia', 'standard', null, null, null, null),
  ('Should Woolworths come back?', 'Nostalgia', 'standard', null, null, null, null),
  ('Were sweets better when you were a kid?', 'Nostalgia', 'standard', null, null, null, null),
  ('Did you ever tape songs off the radio?', 'Nostalgia', 'standard', null, null, null, null),
  ('Was the Millennium Bug overhyped?', 'Nostalgia', 'standard', null, null, null, null),
  ('Would you go back to being 16 for a day?', 'Nostalgia', 'standard', null, null, null, null),
  ('Was Saturday morning TV better in the 90s?', 'Nostalgia', 'standard', null, null, null, null),
  ('Is everything just a reboot now?', 'Nostalgia', 'standard', null, null, null, null),
  ('Should billionaires exist?', 'Politics', 'sensitive', null, null, null, null),
  ('Should 16-year-olds be able to vote?', 'Politics', 'sensitive', null, null, null, null),
  ('Should the House of Lords be abolished?', 'Politics', 'sensitive', null, null, null, null),
  ('Should Scotland be independent?', 'Politics', 'sensitive', null, null, null, null),
  ('Should the UK switch to proportional representation?', 'Politics', 'sensitive', null, null, null, null),
  ('Should there be a wealth tax on the richest?', 'Politics', 'sensitive', null, null, null, null),
  ('Is immigration to the UK too high?', 'Politics', 'sensitive', null, null, null, null),
  ('Should MPs be banned from having second jobs?', 'Politics', 'sensitive', null, null, null, null),
  ('Should the BBC licence fee be scrapped?', 'Politics', 'sensitive', null, null, null, null),
  ('Should private schools pay VAT?', 'Politics', 'sensitive', null, null, null, null),
  ('Should faith schools get state funding?', 'Politics', 'sensitive', null, null, null, null),
  ('Does everything happen for a reason?', 'Beliefs', 'standard', null, null, null, null),
  ('Do you believe in fate?', 'Beliefs', 'standard', null, null, null, null),
  ('Do you believe in karma?', 'Beliefs', 'standard', null, null, null, null),
  ('Do you read your horoscope?', 'Beliefs', 'standard', null, null, null, null),
  ('Does your star sign say anything about you?', 'Beliefs', 'standard', null, null, null, null),
  ('Are you superstitious?', 'Beliefs', 'standard', null, null, null, null),
  ('Is religion a force for good?', 'Beliefs', 'sensitive', null, null, null, null),
  ('Do you believe in heaven?', 'Beliefs', 'sensitive', null, null, null, null),
  ('Do you believe in miracles?', 'Beliefs', 'sensitive', null, null, null, null),
  ('Does life have a meaning beyond what we give it?', 'Beliefs', 'sensitive', null, null, null, null),
  ('Should football bring in sin bins?', 'Sport', 'standard', null, null, null, null),
  ('Should footballers'' wages be capped?', 'Sport', 'standard', null, null, null, null),
  ('Should countries with poor human rights records host the World Cup?', 'Sport', 'standard', null, null, null, null),
  ('Are penalty shootouts a fair way to settle a match?', 'Sport', 'standard', null, null, null, null),
  ('Is Test cricket too long?', 'Sport', 'standard', null, null, null, null),
  ('Is the Premier League the best league in the world?', 'Sport', 'standard', null, null, null, null),
  ('Are F1 drivers real athletes?', 'Sport', 'standard', null, null, null, null),
  ('Is it OK to support a team you have no connection to?', 'Sport', 'standard', null, null, null, null),
  ('League title or FA Cup?', 'Sport', 'standard', 'League', 'Cup', '🏆', '🥇'),
  ('Federer or Nadal?', 'Sport', 'standard', 'Federer', 'Nadal', '🇨🇭', '🇪🇸'),
  ('Is Lewis Hamilton the greatest F1 driver ever?', 'Sport', 'standard', null, null, null, null),
  ('Are voice notes annoying?', 'Tech', 'standard', null, null, null, null),
  ('Dark mode or light mode?', 'Tech', 'standard', 'Dark', 'Light', '🌑', '☀️'),
  ('Should phones be banned in schools?', 'Tech', 'standard', null, null, null, null),
  ('Is screen time damaging children''s brains?', 'Tech', 'standard', null, null, null, null),
  ('Is it OK to use AI to write a wedding speech?', 'Tech', 'standard', null, null, null, null),
  ('Is it OK to post photos of your kids online?', 'Tech', 'standard', null, null, null, null),
  ('Do you trust AI chatbots to tell you the truth?', 'Tech', 'standard', null, null, null, null),
  ('Is it rude to check your phone at dinner?', 'Tech', 'standard', null, null, null, null),
  ('Have you ever read the terms and conditions?', 'Tech', 'standard', null, null, null, null),
  ('Mac or PC?', 'Tech', 'standard', 'Mac', 'PC', '🍏', '🖥️'),
  ('Should apps be allowed to track your location?', 'Tech', 'standard', null, null, null, null),
  ('Should you clap when the plane lands?', 'Travel', 'standard', null, null, null, null),
  ('Is it OK to reserve a sunbed with a towel at 6am?', 'Travel', 'standard', null, null, null, null),
  ('Does the middle seat get both armrests?', 'Travel', 'standard', null, null, null, null),
  ('Should planes have child-free zones?', 'Travel', 'standard', null, null, null, null),
  ('Would you go on a cruise?', 'Travel', 'standard', null, null, null, null),
  ('Is all-inclusive a proper holiday?', 'Travel', 'standard', null, null, null, null),
  ('Should tourists pay a tourist tax?', 'Travel', 'standard', null, null, null, null),
  ('Should you fly less to help the climate?', 'Travel', 'standard', null, null, null, null),
  ('Would you take a 12-hour train instead of a 2-hour flight?', 'Travel', 'standard', null, null, null, null),
  ('Do you unpack as soon as you arrive?', 'Travel', 'standard', null, null, null, null),
  ('Backpacking or luxury?', 'Travel', 'standard', 'Backpacking', 'Luxury', '🎒', '🛎️'),
  ('One horse-sized duck or 100 duck-sized horses?', 'Wild cards', 'standard', 'The duck', 'The horses', '🦆', '🐴'),
  ('Could 100 men beat one gorilla?', 'Wild cards', 'standard', null, null, null, null),
  ('Could you land a plane if the pilots passed out?', 'Wild cards', 'standard', null, null, null, null),
  ('Could you win a fight with a goose?', 'Wild cards', 'standard', null, null, null, null),
  ('Would you survive a zombie apocalypse?', 'Wild cards', 'standard', null, null, null, null),
  ('Invisible or able to fly?', 'Wild cards', 'standard', 'Invisible', 'Fly', '👻', '🦅'),
  ('Would you want to know what everyone really thinks of you?', 'Wild cards', 'standard', null, null, null, null),
  ('Would you eat a spider for £1,000?', 'Wild cards', 'standard', null, null, null, null),
  ('Would you go to space if it was free?', 'Wild cards', 'standard', null, null, null, null),
  ('Are you the main character in your friend group?', 'Wild cards', 'standard', null, null, null, null),
  ('Could you go a week without your phone?', 'Wild cards', 'standard', null, null, null, null),
  ('Is quiet quitting OK?', 'Work', 'standard', null, null, null, null),
  ('Should you be paid for your commute?', 'Work', 'standard', null, null, null, null),
  ('Is it OK to ignore work messages after hours?', 'Work', 'standard', null, null, null, null),
  ('Should you be friends with your boss?', 'Work', 'standard', null, null, null, null),
  ('Is it OK to take a sick day for your mental health?', 'Work', 'standard', null, null, null, null),
  ('Is it OK to date a coworker?', 'Work', 'standard', null, null, null, null),
  ('Would you let your boss track your screen?', 'Work', 'standard', null, null, null, null),
  ('Do you pretend to be busy at work?', 'Work', 'standard', null, null, null, null),
  ('Should unpaid internships be banned?', 'Work', 'standard', null, null, null, null),
  ('Is a degree worth the debt?', 'Work', 'standard', null, null, null, null),
  ('Are work socials forced fun?', 'Work', 'standard', null, null, null, null),
  ('Left Twix or Right Twix?', 'Brands', 'standard', 'Left', 'Right', '⬅️', '➡️'),
  ('Greggs or Pret?', 'Brands', 'standard', 'Greggs', 'Pret', '🥐', '⭐'),
  ('Aldi or Lidl?', 'Brands', 'standard', 'Aldi', 'Lidl', '🛒', '🟡'),
  ('KFC or Nando''s?', 'Brands', 'standard', 'KFC', 'Nando''s', '🍗', '🌶️'),
  ('Cadbury or Galaxy?', 'Brands', 'standard', 'Cadbury', 'Galaxy', '💜', '🌌'),
  ('Domino''s or Papa John''s?', 'Brands', 'standard', 'Domino''s', 'Papa John''s', '🍕', '🍕'),
  ('Is Wetherspoons a proper pub?', 'Brands', 'standard', null, null, null, null),
  ('Could you tell Heinz beans from own-brand in a blind test?', 'Brands', 'standard', null, null, null, null),
  ('Would you boycott a brand over its politics?', 'Brands', 'standard', null, null, null, null),
  ('Is Ryanair worth the hassle for the price?', 'Brands', 'standard', null, null, null, null)
) as v(text, category, sensitivity, option_yes, option_no, emoji_yes, emoji_no)
where not exists (select 1 from public.questions q where lower(q.text) = lower(v.text));

notify pgrst, 'reload schema';
